CCUtils.run("no_miapi", () => {
    const version = 3
    const disabled_files = [
        "crystal/lapis",
        "crystal/nether_quartz",
        "custom/banner_material",
        "custom/chorus_fruit",
        "custom/conduit",
        "custom/copper_rod",
        "custom/end_crystal",
        "custom/ender_pearl",
        "custom/gunpowder",
        "custom/heart_of_the_sea",
        "custom/ice",
        "custom/lingering_potion",
        "custom/nether_star",
        "custom/slime_ball",
        "custom/splash_potion",
        "custom/tnt",
        "custom/rainbow/rainbow_1",
        "custom/rainbow/rainbow_2",
        "custom/rainbow/rainbow_3",
        "custom/rainbow/rainbow_4",
        "custom/rainbow/rainbow_5",
        "custom/rainbow/flags/flag_ace",
        "custom/rainbow/flags/flag_bi",
        "custom/rainbow/flags/flag_gay",
        "custom/rainbow/flags/flag_lesbian",
        "custom/rainbow/flags/flag_nb",
        "custom/rainbow/flags/flag_trans",
        "fabric/kelp",
        "fabric/phantom_membrane",
        "fabric/rabbit_hide",
        "fabric/twisting_vine",
        "fabric/vine",
        "fabric/weeping_vine",
        "fletching/feather",
        "glass/black_glass",
        "glass/blue_glass",
        "glass/brown_glass",
        "glass/cyan_glass",
        "glass/glass",
        "glass/gray_glass",
        "glass/green_glass",
        "glass/light_blue",  // sic
        "glass/light_gray_glass",
        "glass/lime_glass",
        "glass/magenta_glass",
        "glass/orange_glass",
        "glass/pink_glass",
        "glass/purple_glass",
        "glass/red_glass",
        "glass/tinted_glass",
        "glass/white_glass",
        "glass/yellow_glass",
        "metal/copper",
        "metal/gold",
        "rod/blaze_rod",
        "rod/end_rod",
        "stone/andesite",
        "stone/blackstone",
        "stone/calcite",
        "stone/deepslate",
        "stone/diorite",
        "stone/dripstone",
        "stone/end_stone",
        "stone/granite",
        "stone/magma",
        "stone/nether_brick",
        "stone/netherrack",
        "stone/prismarine",
        "stone/purpur_block",
        "stone/red_sandstone",
        "stone/redstone",
        "stone/sandstone",
        "stone/sculk",
        "stone/stone",
        "wood/bamboo",
        "wood/wood",  // generic #minecraft:planks is here
    ]

    CCUtils.versioned("no_miapi", version, () => {
        for (const f of disabled_files) {
            const noOp = { load_condition: { type: "not", condition: { type: "true" } } }
            JsonIO.write(`kubejs/data/miapi/materials/${f}.json`, noOp)
        }

        return true
    })
})
